version: '3.9'

services:
  pg:
    container_name: postgres
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
    ports:
      - '5432:5432'
volumes:
  postgres_data:
